### ISSUE TITLE
add support for ES6

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-parser-js#8]
Grammar:
- [X] block-scoped variable declarations (let/const)
- [X] block-level function declarations
- [x] spread arguments (#47; started for array initialisers in #30)
- [x] rest parameters (rolled into #30)
- [x] import and export declarations (#75)
- [x] destructuring (#30)
- [x] classes (#82)
- [x] arrow functions (#24)
- [x] generator functions + yield (#71)
- [x] default function parameters (rolled into #30)
- [x] method definitions (in object literal) (#40)
- [x] binary/octal integer literals (#16)
- [x] noctals (#117)
- [x] shorthand object property notation (#37)
- [x] remove duplicate object property (besides `__proto__`) strict mode restriction (#28)
- [x] computed property names (#26)
- [x] template strings (#27)
- [x] for-of (#29)
- [x] restrict assignment positions to bindings (assignment LHS, catch param, for-in left, etc.) (#30)
- [x] allow missing semicolon after do-while
- [x] `super` calls and `super` member accesses (#100)
- [x] `new.target` (#101)
- [x] extended unicode escapes in strings, templates, and regexps `"\u{123456}"` (#78)
- [ ] ~~validate surrogate pairs in strings, templates, and regexps(deferred)~~
- [x] allow HTML-style comments in Script (not Module) code (#109)
- [x] disallow initialiser in for-in and for-of head (#68)
- [x] finish [shift-spec ES6 milestone](https://github.com/shapesecurity/shift-spec/milestones/ES6)
- [x] add `parseScript` and `parseModule` interfaces (#98)

Verification:
- [x] go through Annex A to confirm we cover the entire grammar
- [x] go through Annex B, C, D, E to confirm we've not missed any incompatibilities
- [x] confirm we have failure tests for each occurrence of "it is a syntax error if"

Create an issue (or comment on an existing one) if you want to start working on one.
